import Footer from "@/components/footer"
import Navbar from "@/components/navbar"

export const metadata = {
  title: "Terms and Conditions | Bascone Foundation",
  description:
    "Read the Terms and Conditions governing the use of the Bascone Foundation platform and services.",
}

export default function TermsAndConditionsPage() {
  return (
    <div>
        <Navbar/>
    <main className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="mx-auto max-w-4xl bg-white shadow-md rounded-lg p-6 md:p-10">
        <h1 className="text-3xl font-bold text-gray-900 mb-6">
          Terms and Conditions
        </h1>

        <section className="space-y-6 text-gray-700 leading-relaxed">
          <p>
            <strong>Electronic Record</strong><br />
            This document is an electronic record in terms of the Information
            Technology Act, 2000, and rules thereunder, as applicable, and the
            amended provisions pertaining to electronic records in various
            statutes, as amended by the Information Technology Act, 2000. This
            electronic record is generated by a computer system and does not
            require any physical or digital signatures.
          </p>

          <p>
            <strong>Platform Ownership</strong><br />
            The Platform is owned by <strong>Bascone Foundation</strong>, a company
            incorporated under the Companies Act, 2013, with its registered
            office at:
          </p>

          <p className="pl-4 border-l-4 border-gray-300">
            Central Jail Road, Tilka Manjhi,<br />
            PO + PS – Tilka Manjhi,<br />
            Dist. – Bhagalpur, Bihar, India,<br />
            PIN – 812001
          </p>

          <p>
            <strong>Terms of Use</strong><br />
            Your use of the Platform and services and tools are governed by the
            following terms and conditions ("Terms of Use"), including the
            applicable policies, which are incorporated herein by reference. If
            you transact on the Platform, you shall be subject to the policies
            applicable to such transactions.
          </p>

          <p>
            <strong>Acceptance of Terms</strong><br />
            By using the Platform, you are contracting with the Platform Owner,
            and these terms and conditions, including the policies, constitute
            your binding obligations.
          </p>

          <p>
            <strong>Modification of Terms</strong><br />
            These Terms of Use can be modified at any time without prior notice.
            It is your responsibility to periodically review these Terms of Use
            to stay informed of updates.
          </p>

          <p>
            <strong>Definitions</strong><br />
            For the purpose of these Terms of Use:
            <br />
            “You”, “Your”, or “User” refers to any natural or legal person who
            agrees to become a user/buyer on the Platform.
          </p>

          <p>
            <strong>Accessing and Using the Platform</strong><br />
            Accessing, browsing, or otherwise using the Platform signifies your
            agreement to all terms and conditions outlined in these Terms of
            Use. Please read them carefully before proceeding.
          </p>

          <p>
            <strong>User Responsibilities</strong><br />
            You agree to provide true, accurate, and complete information during
            and after registration and shall be responsible for all activities
            conducted using your registered account.
          </p>

          <p>
            <strong>Disclaimer of Warranties</strong><br />
            Neither we nor any third parties provide any warranty or guarantee as
            to the accuracy, timeliness, performance, completeness, or
            suitability of the information and materials offered on this website
            or through our Services for any specific purpose. We expressly
            exclude liability for any inaccuracies or errors to the fullest
            extent permitted by law.
          </p>

          <p>
            <strong>Limitation of Liability</strong><br />
            Your use of our Services and the Platform is solely at your own risk.
            We shall not be liable for any damages arising from your use of the
            Platform. It is your responsibility to assess and ensure that the
            Services meet your requirements.
          </p>

          <p>
            <strong>Intellectual Property Rights</strong><br />
            The content of the Platform and Services is proprietary to us. You do
            not have any rights to claim ownership, title, or interest in the
            content.
          </p>

          <p>
            <strong>Unauthorized Use</strong><br />
            Unauthorized use of the Platform or Services may lead to legal
            action in accordance with these Terms of Use and applicable laws.
          </p>

          <p>
            <strong>Payment Terms</strong><br />
            You agree to pay any charges associated with availing of our
            Services.
          </p>

          <p>
            <strong>Prohibited Uses</strong><br />
            You agree not to use the Platform or Services for any illegal or
            prohibited activities under these Terms or applicable Indian laws.
          </p>

          <p>
            <strong>Third-Party Links</strong><br />
            The Platform may contain links to third-party websites. By accessing
            these links, you agree to be governed by their respective terms of
            use and privacy policies.
          </p>

          <p>
            <strong>Transactional Terms</strong><br />
            By initiating a transaction for availing of the Services, you enter
            into a legally binding contract with the Platform Owner.
          </p>

          <p>
            <strong>Indemnification</strong><br />
            You agree to indemnify and hold harmless the Platform Owner, its
            affiliates, and employees from any claims, demands, or penalties
            arising from your breach of these Terms, privacy policy, or any
            applicable laws.
          </p>

          <p>
            <strong>Limitation of Liability</strong><br />
            In no event shall the Platform Owner be liable for any indirect,
            incidental, or consequential damages, including but not limited to:
          </p>

          <ul className="list-disc pl-6">
            <li>Loss of profits or revenue</li>
            <li>Business interruption</li>
            <li>Loss of data or other economic losses</li>
          </ul>

          <p>
            Our liability shall not exceed the amount paid by you for using our
            Services.
          </p>
        </section>
      </div>
    </main>
    <Footer/>
    </div>
  )
}
